DELETE FROM EXERCISE_DAY_PLAN;
DELETE FROM DAY_PLAN;
commit;
ALTER TABLE exercise_day_plan DROP CONSTRAINT exercise_day_plan_day_plan_id_fkey;

DROP TABLE DAY_PLAN;
ALTER TABLE EXERCISE_DAY_PLAN ADD COLUMN DAY DATE;
ALTER TABLE EXERCISE_DAY_PLAN ADD COLUMN PLAN_ID BIGINT;
ALTER TABLE EXERCISE_DAY_PLAN ADD CONSTRAINT FK_EXERCISE_DAYPLAN_PLAN_ID FOREIGN KEY (PLAN_ID) REFERENCES PLAN(PLAN_ID);