CREATE TABLE news (
                      news_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      subtitle VARCHAR(255) NOT NULL,
                      content TEXT NOT NULL,
                      image_url VARCHAR(255),
                      link VARCHAR(255),
                      is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);