CREATE TABLE IF NOT EXISTS users (user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    avatar BYTEA,
                                    username VARCHAR(255) UNIQUE,
                                    password VARCHAR(255) NOT NULL,
                                    email VARCHAR(255) UNIQUE,
                                    name VARCHAR(255) NOT NULL,
                                    surname VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS configurations (configuration_id SERIAL PRIMARY KEY,
                                              date_format INTEGER NOT NULL,
                                              time_format INTEGER NOT NULL,
                                              LANGUAGE INTEGER NOT NULL,
                                              user_id BIGINT,
                                              FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL);

ALTER TABLE configurations ADD CONSTRAINT fk_configuration FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS permissions (permission_id SERIAL PRIMARY KEY,
                                        permission_name VARCHAR(255) NOT NULL);


CREATE TABLE IF NOT EXISTS ROLE (role_id SERIAL PRIMARY KEY,
                                 role_name VARCHAR(255) NOT NULL);


CREATE TABLE IF NOT EXISTS role_permission (role_id BIGINT, permission_id BIGINT,
                                            FOREIGN KEY (role_id) REFERENCES role(role_id),
                                            FOREIGN KEY (permission_id) REFERENCES permissions(permission_id));

CREATE TABLE IF NOT EXISTS user_role (user_id BIGINT, role_id BIGINT,
                                        FOREIGN KEY (user_id) REFERENCES users(user_id),
                                        FOREIGN KEY (role_id) REFERENCES role(role_id));